apiVersion: apps/v1
kind: Deployment
metadata:
  name: apifrontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: apifrontend
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
