apiVersion: apps/v1
kind: Deployment
metadata:
  name: apifrontend
spec:
  template:
    spec:
      containers:
        - name: apifrontend
          volumeMounts:
            - name: inter-service-ca
              mountPath: /etc/apifrontend/inter-service-ca
              readOnly: true
          env:
            - name: TLS_CA_FILE
              value: /etc/apifrontend/tls-ca/ca.crt
      volumes:
        - name: tls-server
          secret:
            secretName: apifrontend-tls
            optional: true
        - name: tls-ca
          secret:
            secretName: apifrontend-ca
            optional: true
        - name: inter-service-ca
          configMap:
            name: inter-service-ca
